services:
  db:
    container_name: pg_db1
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: accounts_db
    volumes:
      - ../postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin1
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@triton.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  rql2expression:
    image: ${DOCKER_REGISTRY-}rql2expression
    build:
      context: RQL2Expression
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=accounts_db;Username=root;Password=root"
